### ISSUE TITLE
Import GitHub repo description

### ISSUE THREAD

**Issue by mbland** [18F/team_api#38]
The `.about.yml` description may be for the project as a whole, but not capture the description of a specific repository. Ostensibly this information will be in the GitHub repository description itself. We should automatically import this into the Team API information in the same way we automatically infer the `github:` property.

**Comment by mbland** [comment]
Also see 18F/Dashboard#279.

**Comment by DavidEBest** [comment]
It looks like there are two places where it would be straightforward to inject this information:

1) In the about_yml gem when we retrieve the .about.yml file.
Pros:
- we already have the repo information, so pulling the description is trivial
- don't have to iterate over the repos again

Cons:
- we'd be injecting the github info into the about data sooner, so the output of the about_yml gem doesn't represent the 'true' contents of the .about.yml file.
- assumes a 1:1 relationship between .about.yml file and repo, since there isn't a way to specify multiple repos in the .about.yml file.

2) In team-api.18f.gov's project_data, where we currently inject the `github` repo name.
Pros: 
- updates the front matter, not the .about.yml data. If there are multiple repos defined in the github key, we can iterate over all of them.

Cons:
- duplicating some of the work (connect + iterate over repos) of the about_yml gem
- will certainly increase build times

Personally, I'm partial to the first option. Thoughts, @mbland?

**Comment by mbland** [comment]
I think the first option is the way to go, injecting it in `AboutYml::AboutFile.collect_repository_data`. In fact, we can even inject the `github:` repo identifier there as well, and remove it from the 18F/team-api.18f.gov code, since it's all right there. I have no problem having the `AboutYml` code inject extra information inferred from the GitHub API itself; in fact, it seems a rather attractive feature.

As an aside, all that team-api.18f.gov `_scripts` code needs to be properly refactored at some point. I'll add a task to our icebox.

**Comment by mbland** [comment]
Done in 18F/about_yml#32, about to be deployed in 18F/team-api.18f.gov#140.

**Comment by mtorres253** [comment]
@mbland can we move to done?

**Comment by mbland** [comment]
Yep! Wasn't sure if you wanted to wait until a sprint meeting or not.
